GET http://localhost:5000/api/v1/user/

###
POST http://localhost:5000/api/v1/auth/register/
Content-Type: application/json

{
   "email":"thanhlongppltn@gmail.com",
   "password":"123435"
}

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
   "email":"thanhlongppltn@gmail.com",
   "password":"123435"
}

###
GET http://localhost:5000/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJ0aGFuaGxvbmdwcGx0bkBnbWFpbC5jb20iLCJyb2xlX2NvZGUiOiJSMiIsImlhdCI6MTcyNDIxNDYzMiwiZXhwIjoxNzI0NDczODMyfQ.6yI1UOBKpQa1fHqQGSHCLY86FK4SPTAeUVJBif7U9e4