GET http://localhost:5000/api/v1/user/

###
POST http://localhost:5000/api/v1/auth/register/
Content-Type: application/json

{
   "email":"admin@gmail.com",
   "password":"Adm1np@ssw0rd"
}

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
   "email":"admin@gmail.com",
   "password":"Adm1np@ssw0rd"
}

###
GET http://localhost:5000/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhZG1pbkBnbWFpbC5jb20iLCJyb2xlX2NvZGUiOiJSMSIsImlhdCI6MTcyNDY3MzY5MiwiZXhwIjoxNzI0OTMyODkyfQ.7FNdRMGV0zPA7v89IxOOC5J4ocoVtVKwQB7k-CCpUp8

###
GET http://localhost:5000/api/v1/insert/

###
GET http://localhost:5000/api/v1/book/